### ISSUE TITLE
Guidelines for contributing out of date

### ISSUE THREAD

**Issue by mduggan** [opscode-cookbooks/fail2ban#19]
A meta-issue.. If I open a ticket here, it asks me to see the guidelines for contributing.  They say to open a ticket in Jira, but Jira tells me to open a ticket here.

I'm pretty sure here is the right location?

**Comment by tas50** [comment]
I've updated the contributing docs to the current version.  In the future I'm going to see if we can just get the cookbook contributing and testing docs hosted on the docs site so we can avoid this.  If someone has an older version of the cookbook in their environment they shouldn't be reading out of data process docs.
