### ISSUE TITLE
Different logpath for CentOS and RHEL on Softlayer

### ISSUE THREAD

**Issue by leonsp** [opscode-cookbooks/fail2ban#28]
The current base images for CentOS and RHEL on Softlayer are logging ssh errors to /var/log/messages rather than /var/log/secure. Because fail2ban is monitoring the other one, the cookbook configuration doesn't work by default:

http://serverfault.com/questions/646167/why-is-fail2ban-not-banning-this-attack/673112

I would suggest modifying the default for the cookbook to monitor both log files for CentOS and RHEL, either by having two paths in the logpath directive or defining two separate jails, one for /var/log/secure and one for /var/log/messages

**Comment by CanOfSpam3** [comment]
I think you just need to override your 'auth_log' to point to the non-standard one

**Comment by tas50** [comment]
There's current a check for RHEL in the attributes file that sets default['fail2ban']['auth_log'].  You can override this attribute to whatever you want and control what fail2ban is using.
